First version
distributed-technologies/filemover-poc pull request #1
Opened 2021-12-14 12:46 UTC by klausenbusk

README rendered: https://github.com/distributed-technologies/filemover-poc/tree/initial-version#readme

2021-12-14 20:11 UTC, skovbakke requested changes
Overall it looks good. Just a few remarks 🤠

2021-12-14 20:11 UTC, skovbakke commented on main.go
> +				}
Not sure I understand this. Do we insist the signatures to have a certain format? and what is this format? If we have a file `foo.bar` it seems that the signature file must be something like `foo.bar.<initials>.sig`.

2021-12-14 20:15 UTC, skovbakke commented
Also, it seems you forgot to follow the ["setup of repository"-guide](https://github.com/distributed-technologies/wiki/blob/main/git/repo_creation.md) from the wiki. Please, rename the head branch to main and add the branch protection rules. 😊

2021-12-15 07:42 UTC, klausenbusk commented on main.go
> +				}
`foo.bar.<initials>.sig` is correct.

2021-12-15 07:48 UTC, klausenbusk commented on main.go
> +				group := keys[keyId].Group
The `checkSignature` function will fail.

> CheckDetachedSignature takes a signed file and a detached signature and returns the signer if the signature is valid. If the signer isn't known, ErrUnknownIssuer is returned.

https://pkg.go.dev/golang.org/x/crypto/openpgp#CheckDetachedSignature

2021-12-15 19:02 UTC, skovbakke approved these changes
LGTM 🎉

2021-12-17 12:22 UTC, jacobcrawford approved these changes
Since the functionality has been approved by the owner, and it is a POC, I don't think it makes much sense to make improvements. The current state is acceptable.

2021-12-17 12:44 UTC, merged